# src/holdem/__init__.py
"""
holdem — Texas Hold’em engine.

This package contains the classes and functions for Texas Hold'em Poker.

Subpackages:
- holdem.core        : enums, cards, evaluator
- holdem.table       : table, player, pots, buttons_blinds, peek
- holdem.engine      : game, betting, allocate_pots, showdown
- holdem.strategies  : base, features, simple

- holdem.utils       : rng, errors
- holdem.io          : cli, hh_writer
"""

from __future__ import annotations
from importlib.metadata import PackageNotFoundError, version as _pkg_version
try:
    __version__ = _pkg_version("holdem")
except PackageNotFoundError:  # pragma: no cover - fallback for editable installs
    try:
        from ._version import version as __version__  # generated by setuptools_scm during sdist/bdist
    except Exception:
        __version__ = "0+unknown"

# package logger
import logging
logger = logging.getLogger(__name__)

from .core import Suit, Rank, HandRank, GameState, Action, Position, Card, Deck, evaluate_player_hand, HandEval

from .table import Table, TableID, Player, PlayerID, Pot, PotID, Buttons, advance_buttons_post_blinds, peek_buttons

from .engine import Hand, orchestrate_betting_round, chips_to_pots, showdown

from .strategies import Decision, View, Strategy, Features, evaluate_hand_features, CallingStation, Nit, Tag, Lag

from .utils import RNG, DEFAULT_RNG, TableStateError, PotsStateError, EngineStateError

# from .io import main as cli_main, HHWriter as HandHistoryWriter  # optional convenience

__author__ = "Shaun Breedon"
__license__ = "MIT"

__all__ = [
    "__version__", "logger",
    # core
    "Suit", "Rank", "HandRank", "GameState", "Action", "Position",
    "Card", "Deck", "evaluate_player_hand", "HandEval",
    # table
    "Table", "TableID", "Player", "PlayerID", "Pot", "PotID",
    "Buttons", "advance_buttons_post_blinds", "peek_buttons",
    # engine
    "Hand", "showdown", "orchestrate_betting_round", "chips_to_pots",
    # strategies
    "Decision", "View", "Strategy", "Features", "evaluate_hand_features",
    "CallingStation", "Nit", "Tag", "Lag",
    # utils
    "RNG", "DEFAULT_RNG",
    "TableStateError", "PotsStateError", "EngineStateError"
    # io
    # "cli_main", "HandHistoryWriter"
]
